name:
    build-tauri-linux
on:
    pull_request:
        branches:
            main
permissions:
    contents: read
jobs:
    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - name: Setup node.js
              uses: actions/setup-node@v4
              with:
                node-version: latest
            - name: Setup rust
              uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
            - name: Install system dependencies
              run: |
                sudo apt-get update
                sudo apt-get install -y libwebkit2gtk-4.1-dev librsvg2-dev patchelf #libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev
            - name: Install node.js dependencies
              run:
                npm install
            - name: Copy dummy .env
              run:
                cp .env.dummy .env.local
            - name: Build
              run:
                npm exec tauri build --verbose --ci

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                name: artifacts
                path: "src-tauri/target/release/fairplay-app"
